# Generated by Django 4.1.3 on 2022-12-01 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('the_labyrinthe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='heure',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
