# Generated by Django 4.1.3 on 2022-12-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_labyrinthe', '0002_equipe_heure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('up', models.BooleanField()),
                ('down', models.BooleanField()),
                ('left', models.BooleanField()),
                ('right', models.BooleanField()),
            ],
        ),
    ]
