# Generated by Django 4.1.3 on 2022-12-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_labyrinthe', '0004_room_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='score',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
