# Generated by Django 4.1.3 on 2022-12-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_labyrinthe', '0006_remove_room_score_equipe_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='time_played',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True),
        ),
    ]
